### ISSUE TITLE
Tmp files are not properly garbage-collected

### ISSUE THREAD

**Issue by tim-kos** [tus/tusd#250] opened 2019-03-14 08:38 UTC
```
ubuntu at gold@eu-west-1-aws in /srv on ****
$ cd /srv/system__tmp
ubuntu at gold@eu-west-1-aws in /srv/system__tmp on ****
$ du -sh
53G	.
ubuntu at gold@eu-west-1-aws in /srv/system__tmp on ****
$
```

Had 53GB on them (several GB on other machines) from several days. Somehow they are not cleaned up properly all the time.

**Comment by Acconut** [comment] 2019-03-16 19:51
I don't think this is directly caused by tusd but rather by Transloadit's deployment procedure. When tusd is restarted during a deploy, the old tusd process is not able to clean up its temporary files, so they stick around. On the other hand, the new tusd process didn't create these old temporary files and therefore never deletes them.

I had a look at multiple uploader instances and whenever there were old temporary files from tusd, their modification date lined up perfectly with a deploy. A way to prevent this problem would be to either purge temporary files which are older than a few hours using a cron job. Alternatively, we could `rm /tmp/tusd-s3-tmp-*` before every tusd start *assuming there is only ever one tusd process running on a machine at the same time*.

**Comment by tim-kos** [comment] 2019-03-17 13:15
I see, makes sense.

What are these tmp files? Are these chunks stored on local disk? If so, should they be deleted as soon as a chunk was successfully uploaded to AWS, leaving at most n tmp files on disk when tusd is restarted, where n is the number of concurrent uploads going through tusd at the time?

**Comment by Acconut** [comment] 2019-08-25 17:45
There was a bug in tusd which caused some temporary files to not be cleaned up properly. It was fixed in https://github.com/tus/tusd/pull/299. I also checked a few uploaders and the temporary directories only had a few files in them, all of them were recent. So I guess this issue is resolved.

**Closed by Acconut** 2019-08-25 17:45 UTC

**Comment by leaanthony** [comment] 2020-12-16 22:53
I'm getting the same behaviour for the latest version (v1.4.0). No temp files are being deleted despite uploading successfully to S3. Is this a regression?

**Comment by Acconut** [comment] 2021-01-03 23:49
@leaanthony I am not able to reproduce that. Maybe you are experiencing something similar to https://github.com/tus/tusd/issues/446 and can comment over there with more details and steps to reproduce?
