### ISSUE TITLE
when i run the example, i got an error

### ISSUE THREAD

**Issue by qqqasdwx** [tus/tusd#155] opened 2017-11-03 11:00 UTC
[tusd] event="RequestIncoming" method="POST" path="" 
[tusd] event="UploadCreated" id="8d92ea04a7149a1d4ad66f440c14de93" size="112464" url="http://127.0.0.1:8080/files/8d92ea04a7149a1d4ad66f440c14de93" 
[tusd] event="ResponseOutgoing" status="201" method="POST" path="" 
[tusd] event="RequestIncoming" method="PATCH" path="8d92ea04a7149a1d4ad66f440c14de93" 
[tusd] event="ResponseOutgoing" status="500" method="PATCH" path="8d92ea04a7149a1d4ad66f440c14de93" error="Lockfile created, but doesn't exist"

**Comment by Acconut** [comment] 2017-11-03 14:29
Can you please provide more information about your setup? In particular, the used operating system and whether you use a file system over a network?

**Comment by qqqasdwx** [comment] 2017-11-05 13:48
ubuntu 16.04 
`go get github.com/tus/tusd`
then,i run 
```
package main

import (
	"fmt"
	"net/http"

	"github.com/tus/tusd"
	"github.com/tus/tusd/filestore"
)

func main() {
	// Create a new FileStore instance which is responsible for
	// storing the uploaded file on disk in the specified directory.
	// This path _must_ exist before tusd will store uploads in it.
	// If you want to save them on a different medium, for example
	// a remote FTP server, you can implement your own storage backend
	// by implementing the tusd.DataStore interface.
	store := filestore.FileStore{
		Path: "./uploads",
	}

	// A storage backend for tusd may consist of multiple different parts which
	// handle upload creation, locking, termination and so on. The composer is a
	// place where all those seperated pieces are joined together. In this example
	// we only use the file store but you may plug in multiple.
	composer := tusd.NewStoreComposer()
	store.UseIn(composer)

	// Create a new HTTP handler for the tusd server by providing a configuration.
	// The StoreComposer property must be set to allow the handler to function.
	handler, err := tusd.NewHandler(tusd.Config{
		BasePath:      "/files/",
		StoreComposer: composer,
	})
	if err != nil {
		panic(fmt.Errorf("Unable to create handler: %s", err))
	}

	// Right now, nothing has happened since we need to start the HTTP server on
	// our own. In the end, tusd will start listening on and accept request at
	// http://localhost:8080/files
	http.Handle("/files/", http.StripPrefix("/files/", handler))
	err = http.ListenAndServe(":8080", nil)
	if err != nil {
		panic(fmt.Errorf("Unable to listen: %s", err))
	}
}

```

And i try upload file with https://github.com/eventials/go-tus

**Comment by qqqasdwx** [comment] 2017-11-05 13:49
go 1.7

**Comment by qqqasdwx** [comment] 2017-11-05 13:50
my running environment is go 1.9

**Comment by qqqasdwx** [comment] 2017-11-05 13:51
and i use filestore

**Comment by qqqasdwx** [comment] 2017-11-06 03:21
and my file tree 
.
├── client
│   ├── client
│   ├── client.go
│   └── my-file.txt
└── server
    ├── server
    ├── server.go
    └── uploads

**Comment by qqqasdwx** [comment] 2017-11-06 03:21
.
├── client
│   ├── client
│   ├── client.go
│   └── my-file.txt
└── server
    ├── server
    ├── server.go
    └── uploads

**Comment by qqqasdwx** [comment] 2017-11-06 06:21
I will deploy my program on the server, it can run, is my file permissions set right?

**Comment by Acconut** [comment] 2017-11-06 09:35
> is my file permissions set right?

Good thinking, however, your file tree does not contain information about file permissions. Please run `ls -lR` and provide the output.

**Comment by qqqasdwx** [comment] 2017-11-06 09:56
Thanks for your reply, this is my directory structure
and i use root run the server

```
.:
总用量 6762
drwxrwxrwx 1 root root       0 11月  6 14:10 ./
drwxrwxrwx 1 root root       0 11月  3 15:59 ../
-rwxrwxrwx 1 root root 6917533 11月  6 14:10 server*
-rwxrwxrwx 1 root root    1603 11月  6 13:54 server.go*
drwxrwxrwx 1 root root    4096 11月  6 13:56 uploads/

./uploads:
总用量 8
drwxrwxrwx 1 root root 4096 11月  6 13:56 ./
drwxrwxrwx 1 root root    0 11月  6 14:10 ../
-rwxrwxrwx 1 root root    0 11月  6 13:43 4a4d0e304d565b73bd21b4f9fb5b25c4.bin*
-rwxrwxrwx 1 root root  160 11月  6 13:43 4a4d0e304d565b73bd21b4f9fb5b25c4.info*
-rwxrwxrwx 1 root root    0 11月  6 13:53 4bfc003bfd16fa19423bf30cdfc9a69f.bin*
-rwxrwxrwx 1 root root  159 11月  6 13:53 4bfc003bfd16fa19423bf30cdfc9a69f.info*
-rwxrwxrwx 1 root root    0 11月  6 13:42 738bfca8f26a4c0d64de1667a1d9a95c.bin*
-rwxrwxrwx 1 root root  160 11月  6 13:42 738bfca8f26a4c0d64de1667a1d9a95c.info*
-rwxrwxrwx 1 root root    0 11月  6 13:56 8085ec9fb5bdecbac4e22d442ec4e9d1.bin*
-rwxrwxrwx 1 root root  159 11月  6 13:56 8085ec9fb5bdecbac4e22d442ec4e9d1.info*
-rwxrwxrwx 1 root root    0 11月  6 13:41 8b1038ec31ca51863c2bdee908224ac2.bin*
-rwxrwxrwx 1 root root  160 11月  6 13:41 8b1038ec31ca51863c2bdee908224ac2.info*
-rwxrwxrwx 1 root root    0 11月  6 13:47 a134edd5c041c7d4ff436f52b4971989.bin*
-rwxrwxrwx 1 root root  159 11月  6 13:47 a134edd5c041c7d4ff436f52b4971989.info*
-rwxrwxrwx 1 root root    0 11月  6 13:42 e835a07b27d4767b42c60f8c47b733fb.bin*
-rwxrwxrwx 1 root root  160 11月  6 13:42 e835a07b27d4767b42c60f8c47b733fb.info*
```

**Comment by Acconut** [comment] 2017-11-10 19:34
Although it's not recommended to use `0777` for uploaded files, I don't think that this should be a problem. I attempted to reproduce your issue but I wasn't able to. What file system are you using? Could you please provide the output of `df -T`?

**Comment by Acconut** [comment] 2018-03-12 21:24
Closing this issue due to a lack of information. Feel free to leave a comment if you want to continue the discussion :)

**Closed by Acconut** 2018-03-12 21:24 UTC
