### ISSUE TITLE
s3store strips ID value from .info file

### ISSUE THREAD

**Issue by trickkiste** [tus/tusd#138] opened 2017-07-12 20:58 UTC
When I use filestore, I get something like this:
{"ID":"fa551c95d1a502ca78fc6227a70f5561","Size":86406,"Offset":0,"MetaData":{},"IsPartial":false,"IsFinal":false,"PartialUploads":null}

When I use s3store, the ID value is missing in the .info file:
{"ID":"","Size":22479312,"Offset":0,"MetaData":{},"IsPartial":false,"IsFinal":false,"PartialUploads":null}

**Comment by Acconut** [comment] 2017-07-15 20:01
Good catch. It should be possible to reorder the NewUpload function (https://github.com/tus/tusd/blob/master/s3store/s3store.go#L166) so that we know the upload ID when the .info file is created. Basically the calls to CreateMultipartUpload and PutObject should happen in the opposite order. I haven't confirmed this theory yet but I am pretty sure it would work.

**Comment by trickkiste** [comment] 2017-07-15 20:06
That was exactly my thinking as well. But as I was not sure, if there might be a reason for this order, I preferred to provide a more unobtrusive patch first.

**Comment by Acconut** [comment] 2017-07-15 20:11
Great to hear, are you willing to attempt this patch? I would be pleased to assist you :)

**Comment by trickkiste** [comment] 2017-07-15 20:16
Should be as easy as moving the following part downwards below `id = uploadId + "+" + *res.UploadId`, right? 

```
	// Create object on S3 containing information about the file
	_, err = store.Service.PutObject(&s3.PutObjectInput{
		Bucket:        aws.String(store.Bucket),
		Key:           aws.String(uploadId + ".info"),
		Body:          bytes.NewReader(infoJson),
		ContentLength: aws.Int64(int64(len(infoJson))),
	})
	if err != nil {
		return "", fmt.Errorf("s3store: unable to create info file:\n%s", err)
	}
```
Sure I would attempt that. Can provide the patch in a minute. Do you see any other obstacles?

**Comment by Acconut** [comment] 2017-07-15 20:20
> Should be as easy as moving the following part downwards below `id = uploadId + "+" + *res.UploadId`, right?

Yes, but please remember to assign `info.ID = id` before calling `PutObject`.

> Do you see any other obstacles?

Except for tests, I don't :)

**Comment by trickkiste** [comment] 2017-07-15 20:26
OK, I'll attempt this patch then.

As for the tests, copy that. I have not seen any tests explicitly testing
for the existence of the ID value in the .info file. Neither in filestore
nor in s3store. I have added some to filestore, but have not made a patch
yet. Nor have I figured out yet, how to test this with S3.

BTW, how frequently do you guys meet to chat on Slack?

Mit besten Grüßen,
Markus Kienast

--

Markus Kienast - CEO

FLANEUR TV
<mark@sfe.tv>mark@f <mark@trickkiste.at>laneur.tv
+43 699 18084401

Commercial Register: FN 363780 x
UID: ATU66601545
WWW: http:// <http://trickkiste.at/>flaneur.tv

2017-07-15 22:20 GMT+02:00 Marius <notifications@github.com>:

**Comment by Acconut** [comment] 2017-07-15 20:32
The tests could be incomplete here because of how the ID has been stored previously in the .info file.
However, I was talking about the tests are also sensitive to the order of when calls to the S3 API are made. And this needs adjustments, see https://github.com/tus/tusd/blob/master/s3store/s3store_test.go#L41.

> BTW, how frequently do you guys meet to chat on Slack?

We usually have an eye on it daily (except for weekends, holidays and so on) and are happy to welcome you there :)

**Comment by trickkiste** [comment] 2017-07-15 21:11
Potentially there is another issue bubbling up here. Depends on this section:
```
	var uploadId string
	if info.ID == "" {
		uploadId = uid.Uid()
	} else {
		uploadId = info.ID
	}
``` 

In which case would info.ID already have a value? Or is the else obsolete anyways?

If in any case, we would run through 
`func (store S3Store) NewUpload(info tusd.FileInfo) (id string, err error) {}` again and do a `id = uploadId + "+" + *res.UploadId
  info.ID = id`
at the end, we will append to +*res.UploadId with each run.

**Comment by Acconut** [comment] 2017-07-15 21:21
> In which case would info.ID already have a value?

Is is used in testing where we need to have an upload ID which is not calculated randomly but statically, if I recall correctly.

> If in any case, we would run through
`func (store S3Store) NewUpload(info tusd.FileInfo) (id string, err error) {}` again and do a `id = uploadId + "+" + *res.UploadId info.ID = id`
at the end, we will append to +*res.UploadId with each run.

I think, this is acceptable. If you invoke NewUpload with an ID, it will use this ID as the object ID for S3 and not the full upload ID.

**Comment by trickkiste** [comment] 2017-07-15 21:25
Alright, I was just wondering.

Mit besten Grüßen,
Markus Kienast

--

Markus Kienast - CEO

FLANEUR TV
<mark@sfe.tv>mark@f <mark@trickkiste.at>laneur.tv
+43 699 18084401

Commercial Register: FN 363780 x
UID: ATU66601545
WWW: http:// <http://trickkiste.at/>flaneur.tv

2017-07-15 23:21 GMT+02:00 Marius <notifications@github.com>:

**Comment by Acconut** [comment] 2017-07-20 08:13
Fixed in https://github.com/tus/tusd/pull/142.

**Closed by Acconut** 2017-07-20 08:13 UTC
