### ISSUE TITLE
Upgrade log/slog

### ISSUE THREAD

**Issue by pcfreak30** [tus/tusd#1201] opened 2024-10-07 22:31 UTC
I had to upgrade `golang.org/x/exp/slog` to `log/slog` earlier this year, though I forgot the technical reason.

I would like to request this be done since the package seems to have graduated.

**Comment by Acconut** [comment] 2024-10-08 14:22
This is planned for the [next major release](https://github.com/tus/tusd/milestone/1). Closing as a duplicate of https://github.com/tus/tusd/pull/1159.

**Closed by Acconut** 2024-10-08 14:22 UTC
Labels: bug

**Comment by srerickson** [comment] 2025-07-25 18:06
I noticed that `handler.Config` is still using golang.org/x/exp/slog
