### ISSUE TITLE
s3store: Cannot set Content-Disposition

### ISSUE THREAD

**Issue by pfilaretov42** [tus/tusd#978] opened 2023-07-13 15:20 UTC
**Question**
Hi, I'm using tusd in a system where users can upload files into S3-compatible cloud storage. Then, a user may want to download file back in the browser by the signed URL to the file on S3. So, in the browser's save dialog I want a file name and file extension to be set as in the original file. It can be done, if I set the following file metadata in the cloud storage:

|Name|Value|
|---|---|
|ContentDisposition|attachment; filename="myFile.mov"|

However, when I try to pass `ContentDisposition` metadata in the `Upload-Metadata` request header, it gets converted to lowercase, i.e. `contentdisposition`, and this is how it is saved in the file metadata on S3. And it does not work to provide a file name and file extension on download then.

This is not a tus-js-client problem, because I can see that the `Upload-Metadata` header of the request to tusd is set correctly with `ContentDisposition`, not `contentdisposition`.

Is it possible to configure tusd not to do lowercase conversion of `Upload-Metadata` request header? Is it the expected behaviour?

**Setup details**
- Operating System: running tusd in a docker, from official image: https://hub.docker.com/layers/tusproject/tusd/v1.11.0/images/sha256-db463b74ebb57a7bc959d8ac364dd007bf8fd49d50ede93c0dde885800e74602?context=explore
- Used tusd version: v1.11.0
- Used tusd data storage: AWS S3 compatible
- Used tusd configuration: `-s3-endpoint $BUCKET_ADDRESS -s3-bucket $BUCKET_NAME -metrics-path /admin/prometheus -port=8080 --hooks-http $HOOK_ADDRESS -base-path $BASE_PATH -behind-proxy`
- Used tus client library: tus-js-client 2.3.1

**Comment by Acconut** [comment] 2023-07-14 09:19
I don't see any code that would lower case the metadata keys in tusd, so I would assume that this is maybe even done by S3 itself. However, this should also not matter in this case because header values are usually treated case insensitively.

What might be the problem is that you are using `ContentDisposition` instead of `Content-Disposition`. I am not entirely sure if that is the root cause, but at least the HTTP header is written with a dash.

**Comment by pfilaretov42** [comment] 2023-07-14 09:46
Okay, I'll try to check what S3 does on that, thanks.

I know that the correct HTTP header name is with the dash (`Content-Disposition`), however, when I try to pass it within `Upload-Metadata` it is not saved as a metadata to S3.
On the other hand, when I manually add `ContentDisposition` (CamelCase, no dash) metadata to the file on S3, it gets downloaded with file name and extension info as I want it to. So, it actually works, I just cannot find the way to set this metadata correctly from tusd yet.

**Comment by pfilaretov42** [comment] 2023-07-14 15:16
So, it seems that setting metadata only is not working for `Content-Disposition`.

I had a look at the `CreateMultipartUploadInput` of the AWS S3 go SDK [here](https://docs.aws.amazon.com/sdk-for-go/api/service/s3/#CreateMultipartUploadInput) and it has a separate field `ContentDisposition`. So, I think when the multipart upload is created in `s3store.go`
```go
	// Create the actual multipart upload
	res, err := store.Service.CreateMultipartUploadWithContext(ctx, &s3.CreateMultipartUploadInput{
		Bucket:   aws.String(store.Bucket),
		Key:      store.keyWithPrefix(uploadId),
		Metadata: metadata,
	})
```
it should also set `ContentDisposition` field separately here:
```go
	// Create the actual multipart upload
	res, err := store.Service.CreateMultipartUploadWithContext(ctx, &s3.CreateMultipartUploadInput{
		Bucket:   aws.String(store.Bucket),
		Key:      store.keyWithPrefix(uploadId),
		Metadata: metadata,
		ContentDisposition: ...,
	})
```

I tested setting metadata from AWS S3 java SDK, it also has the separate field for `ContentDisposition` and it works correctly when I set it.

So, I would love if you guys could fix this.

I believe the same applies to `ContentLanguage` metadata/header, and maybe some others.

**Comment by Acconut** [comment] 2023-07-19 06:24
That makes sense. Then we would have to populate these properties. I think we could fill `Content-Disposition` and `Content-Type` from the metadata keys `filename` and `filetype`, like we already do when we respond to GET requests: https://github.com/tus/tusd/blob/b4ffdf43f034099ee46437271de2ff98c1f52397/pkg/handler/unrouted_handler.go#L763-L765

Feel free to open a PR for this! I am not sure when I could work on this.

**Comment by Acconut** [comment] 2024-09-18 09:40
Closing in favor of https://github.com/tus/tusd/issues/1016.

**Closed by Acconut** 2024-09-18 09:40 UTC
Labels: question
