### ISSUE TITLE
Using Docker image can't resume

### ISSUE THREAD

**Issue by s1rc** [tus/tusd#224] opened 2018-12-05 21:40 UTC
Using the Dockerfile to build an image and run tusd, uploads work fine, however resuming files do not.

Does the docker container need an extra volume mounted for temporary files not complete?

**Comment by Acconut** [comment] 2018-12-08 13:53
I personally don't use the Docker image regularly, but this should not happen.

How exactly are you using the tusd server? What client library are you using? Could you supply steps on how we might reproduce this behavior?

> Does the docker container need an extra volume mounted for temporary files not complete?

It needs a disk to write file to but I am not sure if it has to be an extra volume. I am no Docker expert, so I can honestly not answer that question.

**Comment by Acconut** [comment] 2019-01-17 09:04
Closing this issue due to a lack of information. Feel free to leave a comment if you want to continue the discussion :)

**Closed by Acconut** 2019-01-17 09:04 UTC
