### ISSUE TITLE
Random 500 responses

### ISSUE THREAD

**Issue by ifedapoolarewaju** [tus/tusd#259] opened 2019-04-01 12:57 UTC
**Describe the bug**
I am randomly getting 500 responses from `master.tus.io`. I am testing with the tus-js-client, and I randomly get these errors when starting/running an upload:

```
unexpected response while creating upload, originated from request (response code: 500, response text: )
```

```
unexpected response while uploading chunk, originated from request (response code: 500, response text: )
```

in the few times that I've tried against a locally running tusd server, I didn't get the error.

**To Reproduce**
It's random and cannot always be reproduced.
1. Start upload with `tus-js-client` against master.tus.io
2. See error

**Expected behavior**
A successful upload.

**Setup details**
Please provide following details, if applicable to your situation:
- Operating System: whatever OS is running with master.tus.io. Tus-js-client was on macOS
- Used tusd version: I suppose the latest version, as it is running on master.tus.io
- Used tus client library: tus-js-client

**Comment by Acconut** [comment] 2019-04-09 20:13
Thank you for the report. Can you supply the script you used to trigger those errors?

**Comment by arturi** [comment] 2019-04-11 11:01
If it helps, I’m experiencing `423 upload locked` when I add a file about 100mb on the Dashboard example https://uppy.io/examples/dashboard/ and pause/resume multiple times. 

And @nqst could you share more details here, please.

**Comment by Acconut** [comment] 2019-04-11 11:34
@arturi That's unrelated to the issue from Ife but I have an idea. What values are you using for tus-js-client's retryDelays?

**Comment by arturi** [comment] 2019-04-11 11:35
I think the default ones `retryDelays: [0, 1000, 3000, 5000]`, as set in `@uppy/tus`.

**Comment by Acconut** [comment] 2019-04-11 11:40
Ok, I will later today change a setting for master.tus.io which might help you with the resuming. I will let you know then.

**Comment by arturi** [comment] 2019-04-11 12:09
Thank you!

**Comment by nqst** [comment] 2019-04-11 12:25
I experienced this (or similar) issue several times. First testing:
- Uppy was stuck while saying that uploading is in progress; retry button appeared but didn't work (screenshare: https://transloadit.slack.com/files/U4D4GMZ5H/FHD7FHZ2M/uppy_uploading_stuck.mov)
- Seems resumable upload didn't work after big pause (in my case ~2min)
- Error codes I got: `423` (first attempt), `409` (second attempt)

Second testing (locally; after pausing and then resuming quickly):
![Screen Recording 2019-04-11 at 11 49](https://user-images.githubusercontent.com/375537/55956855-999e7480-5c6d-11e9-898b-f5630b0ebcf6.gif)

Third testing:
![image](https://user-images.githubusercontent.com/375537/55956990-e8e4a500-5c6d-11e9-8740-b50a30c219ef.png)

**Comment by Acconut** [comment] 2019-04-11 17:55
Thank you for the detail.  I decreased the read timeout for master.tus.io from 30s to 6s. This means that (in the worst situation) an upload is now only locked for 6s instead of 30s. If you have setup tus-js-client with `retryDelays: [0, 1000, 3000, 5000]` it should be always able to recover from a 423 Locked response (as the last retry happens after 9s where the upload should be unlocked).

@nqst I would have a two questions:
* What does "locally" mean in your case? Was tusd and/or Companion running on your local machine?
* Which component did the actual upload to tusd? Was it your browser or Companion (I suppose later one)?

**Comment by Acconut** [comment] 2019-04-11 20:15
I did a debugging round and found a few points worth mentioning:

* The 500 Internal Server Error responses are likely coming from I/O timeouts while reading from the HTTP connection. We cannot really prevent them since they are caused by your uplink's throughput and latency. However, tus-js-client should be able to handle those without much problems if you setup `retryDelays`.
* The 409 Conflict (Mismatching Upload Offset) responses were caused by a deployment issue from master.tus.io. The problem was that we were running two tusd instances for redundancy. However, each tusd instance also holds upload locks in memory which are obviously not shared between the tusd instances. This caused uploads to appear unlocked while they should actually be locked, which resulted in 409 responses in the most time. Anyways, the deployment was fixed, so those should not appear anymore.
* The 423 Locked responses are correctly returned by the server. However, I found an issue in tus-js-client were it will not retry an upload if the server responded with an 4XX response. This rule makes sense in some cases but not for 423 Locked responses. I will release a tus-js-client 1.7.1 very soon which addresses this problem. Please update Uppy/Companion then and those problems should not occur again (or at least less often).

**Comment by Acconut** [comment] 2019-04-11 21:02
Ok, tus-js-client 1.7.1 has been released.

**Comment by nqst** [comment] 2019-04-12 07:25
> What does "locally" mean in your case? Was tusd and/or Companion running on your local machine?

I have Companion installed since the second testing, but on the first testing, I used Uppy, without tusd and Companion installed.

> Which component did the actual upload to tusd? Was it your browser or Companion (I suppose later one)?

Don't know, unfortunately. If it depends only on having Companion installed, then it was Companion probably (again, since the second testing).

**Comment by Acconut** [comment] 2019-09-16 16:53
I am closing this issue since I believe the major issues should be fixed. Feel free to leave a comment if the problems are still persisting.

**Closed by Acconut** 2019-09-16 16:53 UTC
Labels: bug
