### ISSUE TITLE
Set s3 storage path Based on the response from Hooks?

### ISSUE THREAD

**Issue by alameenlr** [tus/tusd#330] opened 2019-12-02 04:41 UTC
I want to set s3 ```ObjectPrefix``` based on pre-create response from hooks?
Is the ```<upload id>``` unique for ever?

**Comment by Acconut** [comment] 2019-12-02 09:12
This is not possible. You cannot define the S3 storage path from a hook. However, you can store the uploads at a temporary location on S3 and then rename them inside the post-finish hook once the upload is complete.

**Comment by alameenlr** [comment] 2019-12-02 09:18
tusd generated ```upload id``` is it unique forever?

**Comment by Acconut** [comment] 2019-12-02 10:38
The ID is a randomly generated 16-byte string (see https://github.com/tus/tusd/blob/master/internal/uid/uid.go). Theoretically, it will not be unique *forever* and collision can occur but in real-world scenarios these are extremely unlikely. So, it's safe to assume that those IDs are unique.

**Comment by alameenlr** [comment] 2019-12-03 04:35
Could you help me for this?

_go build -o tusd cmd/tusd/main.go_
```
tus/tusd/cmd/tusd/cli/hooks/plugin.go:5:2: cannot find package "plugin" in any of:
    /usr/src/plugin (from $GOROOT)
    /root/go/src/plugin (from $GOPATH)
```
Whats the plugin?

**Comment by Acconut** [comment] 2019-12-03 10:02
Plugin is a package in Go's standard library since Go 1.8. What Go version are you using? You need at least Go 1.12 as mentioned in https://github.com/tus/tusd/blob/master/docs/installation.md#compile-from-source

**Comment by alameenlr** [comment] 2019-12-03 15:21
I've Changed ```go1.10.x``` to ```go version go1.13.4 linux/amd64```
Now.
```compile: version "go1.13.3" does not match go tool version "go1.13.4"```

**Comment by alameenlr** [comment] 2019-12-03 18:07
Working with go version go1.12.13!

**Comment by alameenlr** [comment] 2019-12-04 03:00
I've added additional header for authentication, So
I added one additional header to ```Access-Control-Allow-Headers``` in both 
```pkg\handler\cors_test.go``` & ```pkg\handler\unrouted_handler.go``` ,
My Ubuntu server doesn't shows any errors, and works fine.

In my Windows Desktop(```localhost```).
Shows
![Tus](https://user-images.githubusercontent.com/50786913/70108805-29b38300-1670-11ea-9305-21649b20a9e1.JPG)

**Comment by Acconut** [comment] 2019-12-04 16:01
> compile: version "go1.13.3" does not match go tool version "go1.13.4"

This error is not caused by tusd but you likely have multiple Go versions in your environment, see https://github.com/golang/go/issues/22814 for example.

> Working with go version go1.12.13!

Great, I am happy to read that! So I am going to close this issue then.

**Closed by Acconut** 2019-12-04 16:01 UTC
