### ISSUE TITLE
Slow upload speed

### ISSUE THREAD

**Issue by arrowcircle** [tus/tusd#856] opened 2022-11-21 15:23 UTC
**Question**
Hey! I have a problem with slow upload speed with tusd, it only speeds up to 20-30 mbit/s, while aws cli copies files to the same bucket from the same client with full 100mbit/s. Is it possible to speed up tusd to use full speed? If yes, how can I understand what is slowing tusd?

**Setup details**
Please provide following details, if applicable to your situation:
- Operating System: AWS Kubernetes 1.23 without any constraints of pod, 
- Used tusd version: v1.10
- Used tusd data storage: AWS S3
- Used tusd configuration: - -behind-proxy, -hooks-http-forward-headers, --hooks-enabled-events=pre-create,post-create,post-finish,post-terminate, --hooks-http=https://lala/tusd, -s3-bucket lalala, -s3-object-prefix tusd
- Used tus client library: Uppy.js

**Comment by Acconut** [comment] 2023-02-11 20:31
I think this is a duplicate of https://github.com/tus/tusd/issues/440.

**Closed by Acconut** 2023-02-11 20:31 UTC
Labels: question
