### ISSUE TITLE
File Locked when Terminate is called right after Abort

### ISSUE THREAD

**Issue by ifedapoolarewaju** [tus/tusd#320] opened 2019-11-02 11:02 UTC
**Describe the bug**
using tus-js-client, whenever the `tus.abort(true)` method is called with `true`, it aborts the current request, but then gets a `423` response when it tries to terminate the upload.

A current workaround is to call `tus.abort()` without `true`, and then wait 1 second (`setTimeout`), and then call `tus.abort(true)`

**To Reproduce**
1. Start upload
2. Abort Upload with parameter `true`
3. See `423` error

**Expected behavior**
The server should return a `204` response

**Setup details**
Please provide following details, if applicable to your situation:
- Used tusd: master.tus.io
- Used tus client library: tus-js-client, Uppy.js

**Comment by Acconut** [comment] 2019-11-02 12:24
Good catch, Ife! I am not sure if this can be even solved inside tusd. The problem is that the DELETE request arrives before the PATCH request is aborted because tus-js-client does not wait with the termination until the PATCH request is done. I see two possibilities how this could be fixed inside tus-js-client:

1. Research if XMLHttpRequest provides an event when the request is aborted in such way, that the server is also notified of the request end (not sure if that exists) and only send the DELETE request after that event.
2. Retry the DELETE request if we get a 423 response (or other failures), similar to how other requests are retried.

Would you be willing to look into this?

**Comment by ifedapoolarewaju** [comment] 2019-11-02 15:09
> Research if XMLHttpRequest provides an event when the request is aborted in such way, that the server is also notified of the request end (not sure if that exists) and only send the DELETE request after that event.

This was my first suspicion, but I already tried to implement it, and I still noticed the error. That was why I opened this issue. I'll see if I can try option 2

**Comment by ifedapoolarewaju** [comment] 2019-11-03 11:06
here's a PR https://github.com/tus/tus-js-client/pull/174

**Comment by Acconut** [comment] 2019-12-19 20:52
Closes this as it is fixed in tus-js-client.

**Closed by Acconut** 2019-12-19 20:52 UTC
Labels: bug
