### ISSUE TITLE
Post-finish hook starts before pre-finish hook finishes

### ISSUE THREAD

**Issue by gryphon** [tus/tusd#702] opened 2022-04-06 16:42 UTC
**Describe the bug**
As per documentation Pre-finish file hook could be blocking so TUS will wait until it finishes.
But as we see from TUSD log it usually operated by the following order:
- pre-finish started
- post-finish started
- pre-finish finished 
- post-finish finished
(last 2 lines may be in random order)

**To Reproduce**
It can be reproduced at every upload with pre- and post- finish hooks

**Expected behavior**
Tus should wait until pre-finish hook returns OK

**Setup details**
Docker TUSD 1.9

**Comment by Acconut** [comment] 2022-04-07 07:59
We need more details from you, please. What hooks are you using? filehooks? What are the logs that tusd is producing?

**Comment by gryphon** [comment] 2022-05-11 08:34
Just tried it and got the results for the first uploaded file:

```
[tusd] 2022/05/11 08:30:30.071419 event="HookInvocationStart" type="pre-finish" id="9b832ea6365a3f715f6527c5552e21a6" 
[tusd] 2022/05/11 08:30:30.071524 event="UploadFinished" id="9b832ea6365a3f715f6527c5552e21a6" size="1104193" 
[tusd] 2022/05/11 08:30:30.071537 event="HookInvocationStart" type="post-finish" id="9b832ea6365a3f715f6527c5552e21a6" 
[tusd] 2022/05/11 08:30:31.062397 event="HookInvocationStart" type="post-receive" id="9b832ea6365a3f715f6527c5552e21a6" 
[tusd] 2022/05/11 08:30:31.062892 event="HookInvocationFinish" type="post-receive" id="9b832ea6365a3f715f6527c5552e21a6" 
[tusd] 2022/05/11 08:30:31.262358 event="HookInvocationFinish" type="pre-finish" id="9b832ea6365a3f715f6527c5552e21a6" 
[tusd] 2022/05/11 08:30:31 event="ResponseOutgoing" status="204" method="PATCH" path="9b832ea6365a3f715f6527c5552e21a6" requestId="549bbb90-7252-4960-b0cb-444fd9a70f62" 
[tusd] 2022/05/11 08:30:31.714029 event="HookInvocationFinish" type="post-finish" id="9b832ea6365a3f715f6527c5552e21a6" 

```

As you can see, pre-finish here is finished after post-finish is started

**Comment by Acconut** [comment] 2022-05-23 12:42
Ah, that makes sense and is a bug in tusd. As you can see from the code, the post-finish hook (through the CompleteUploads channel in the code below) is invoked before the `pre-finish` callback is invoked:

https://github.com/tus/tusd/blob/457ca870ea339ef009fb6ea29502cf08db32025b/pkg/handler/unrouted_handler.go#L703-L714

This looks like a bug to me and the order should be switched around. Are you interested in PRing this?

**Comment by gryphon** [comment] 2022-06-14 07:35
Not sure if I can correctly fix this code by myself but I may help with testing :)

**Comment by Acconut** [comment] 2022-06-17 11:08
Should be fixed in master. Feel free to try the latest master branch :)

**Closed** 2022-06-17 11:08 UTC
Labels: bug

**Comment by jdcalvin** [comment] 2022-07-06 22:34
@Acconut Confirmed this change fixes the behavior of the `pre-finish` hook. `post-finish` will now only invoke after `pre-finish` is completed. Any timeline for when this will be released in a new version?

**Comment by Acconut** [comment] 2022-07-25 10:56
@jdcalvin Great, this patch is released in https://github.com/tus/tusd/releases/tag/v1.9.1
